'use strict';

module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('products', [
      {
        product_name: 'Ballpoint Pen',
        product_category_id: 9,
        supplier: 'OfficeMart',
        quantity: 200,
        order_price: 2000,
        sell_price: 3500,
        total_order_price: 400000,
        total_sell_price: 700000,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        product_name: 'A4 Copy Paper',
        product_category_id: 9,
        supplier: 'Paperindo',
        quantity: 50,
        order_price: 40000,
        sell_price: 55000,
        total_order_price: 2000000,
        total_sell_price: 2750000,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        product_name: 'LED Bulb 12W',
        product_category_id: 10,
        supplier: 'BrightLight Co.',
        quantity: 100,
        order_price: 15000,
        sell_price: 25000,
        total_order_price: 1500000,
        total_sell_price: 2500000,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        product_name: 'Safety Helmet',
        product_category_id: 11,
        supplier: 'ProSafety Supplies',
        quantity: 30,
        order_price: 75000,
        sell_price: 110000,
        total_order_price: 2250000,
        total_sell_price: 3300000,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        product_name: 'Packing Tape',
        product_category_id: 12,
        supplier: 'IndoPack',
        quantity: 150,
        order_price: 6000,
        sell_price: 10000,
        total_order_price: 900000,
        total_sell_price: 1500000,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        product_name: 'Hand Pallet Truck',
        product_category_id: 13,
        supplier: 'LiftTech',
        quantity: 5,
        order_price: 1500000,
        sell_price: 2200000,
        total_order_price: 7500000,
        total_sell_price: 11000000,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        product_name: 'Steel Rack (5 Tier)',
        product_category_id: 14,
        supplier: 'MegaRack',
        quantity: 10,
        order_price: 750000,
        sell_price: 1200000,
        total_order_price: 7500000,
        total_sell_price: 12000000,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        product_name: 'Nitrile Gloves Box',
        product_category_id: 11,
        supplier: 'MedSupply',
        quantity: 100,
        order_price: 35000,
        sell_price: 55000,
        total_order_price: 3500000,
        total_sell_price: 5500000,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        product_name: 'Barcode Scanner',
        product_category_id: 13,
        supplier: 'ScanTech',
        quantity: 8,
        order_price: 450000,
        sell_price: 650000,
        total_order_price: 3600000,
        total_sell_price: 5200000,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        product_name: 'Shrink Wrap Roll',
        product_category_id: 12,
        supplier: 'WrapIt',
        quantity: 40,
        order_price: 50000,
        sell_price: 80000,
        total_order_price: 2000000,
        total_sell_price: 3200000,
        created_at: new Date(),
        updated_at: new Date(),
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('products', null, {});
  },
};
